//增加图书分类
insert into  category values('C001', '计算机', '计算机');
insert into  category values('C002', '小说', '小说');
insert into  category values('C003', '心理学', '心理学');
insert into  category values('C004', '电子通讯', '电子通讯');

//增加书籍信息
insert into books values('B001','Docker 容器与容器云', 77.50, 1.0, 'Jucy', '本书从实践者的角度，在讲解Docker高级实践技巧的同时，深入到源代码层次，为读者梳理出Docker容器技术和基于Docker的容器云技术（如Kubernetes）的实现方法和设计思路，帮助读者理解如何在实际场景中利用Docker解决问题并启发新的思考。', '第一部分&nbsp;Docker深入解读<br/>第1章&nbsp;从容器到容器云&nbsp;&nbsp;2<br/>1.1&nbsp;云计算平台&nbsp;&nbsp;2<br/>1.2&nbsp;容器，新的革命&nbsp;&nbsp;3<br/>1.3&nbsp;进化：从容器到容器云&nbsp;&nbsp;7<br/>第2章&nbsp;Docker基础&nbsp;&nbsp;8<br/>2.1&nbsp;Docker的安装&nbsp;&nbsp;8<br/>2.2&nbsp;Docker操作参数解读&nbsp;&nbsp;9<br/>2.3&nbsp;搭建你的第一个Docker应用栈&nbsp;&nbsp;16<br/>2.3.1&nbsp;Docker集群部署&nbsp;&nbsp;16<br/>2.3.2&nbsp;第一个Hello World&nbsp;&nbsp;17<br/>2.3.3&nbsp;开发、测试和发布一体化&nbsp;&nbsp;27', '001.jpg',320,' 人民邮电出版社','2015-09-01',9527); 
insert into books values('B002','Spring MVC学习指南', 39.00, 0.88, 'Leibniz', '本书从实践者的角度，在讲解Docker高级实践技巧的同时，深入到源代码层次，为读者梳理出Docker容器技术和基于Docker的容器云技术（如Kubernetes）的实现方法和设计思路，帮助读者理解如何在实际场景中利用Docker解决问题并启发新的思考。', '第一部分&nbsp;Docker深入解读<br/>第1章&nbsp;从容器到容器云&nbsp;&nbsp;2<br/>1.1&nbsp;云计算平台&nbsp;&nbsp;2<br/>1.2&nbsp;容器，新的革命&nbsp;&nbsp;3<br/>1.3&nbsp;进化：从容器到容器云&nbsp;&nbsp;7<br/>第2章&nbsp;Docker基础&nbsp;&nbsp;8<br/>2.1&nbsp;Docker的安装&nbsp;&nbsp;8<br/>2.2&nbsp;Docker操作参数解读&nbsp;&nbsp;9<br/>2.3&nbsp;搭建你的第一个Docker应用栈&nbsp;&nbsp;16<br/>2.3.1&nbsp;Docker集群部署&nbsp;&nbsp;16<br/>2.3.2&nbsp;第一个Hello World&nbsp;&nbsp;17<br/>2.3.3&nbsp;开发、测试和发布一体化&nbsp;&nbsp;27', '002.jpg',734,' 人民邮电出版社','2015-09-01',2354); 
insert into books values('B003','Spark大数据处理技术', 83.50, 0.9, 'Grwg', '本书从实践者的角度，在讲解Docker高级实践技巧的同时，深入到源代码层次，为读者梳理出Docker容器技术和基于Docker的容器云技术（如Kubernetes）的实现方法和设计思路，帮助读者理解如何在实际场景中利用Docker解决问题并启发新的思考。', '第一部分&nbsp;Docker深入解读<br/>第1章&nbsp;从容器到容器云&nbsp;&nbsp;2<br/>1.1&nbsp;云计算平台&nbsp;&nbsp;2<br/>1.2&nbsp;容器，新的革命&nbsp;&nbsp;3<br/>1.3&nbsp;进化：从容器到容器云&nbsp;&nbsp;7<br/>第2章&nbsp;Docker基础&nbsp;&nbsp;8<br/>2.1&nbsp;Docker的安装&nbsp;&nbsp;8<br/>2.2&nbsp;Docker操作参数解读&nbsp;&nbsp;9<br/>2.3&nbsp;搭建你的第一个Docker应用栈&nbsp;&nbsp;16<br/>2.3.1&nbsp;Docker集群部署&nbsp;&nbsp;16<br/>2.3.2&nbsp;第一个Hello World&nbsp;&nbsp;17<br/>2.3.3&nbsp;开发、测试和发布一体化&nbsp;&nbsp;27', '003.jpg',432,' 人民邮电出版社','2015-09-01',643); 
insert into books values('B004','战长沙', 23.50, 0.75, 'Sony', '本书从实践者的角度，在讲解Docker高级实践技巧的同时，深入到源代码层次，为读者梳理出Docker容器技术和基于Docker的容器云技术（如Kubernetes）的实现方法和设计思路，帮助读者理解如何在实际场景中利用Docker解决问题并启发新的思考。', '第一部分&nbsp;Docker深入解读<br/>第1章&nbsp;从容器到容器云&nbsp;&nbsp;2<br/>1.1&nbsp;云计算平台&nbsp;&nbsp;2<br/>1.2&nbsp;容器，新的革命&nbsp;&nbsp;3<br/>1.3&nbsp;进化：从容器到容器云&nbsp;&nbsp;7<br/>第2章&nbsp;Docker基础&nbsp;&nbsp;8<br/>2.1&nbsp;Docker的安装&nbsp;&nbsp;8<br/>2.2&nbsp;Docker操作参数解读&nbsp;&nbsp;9<br/>2.3&nbsp;搭建你的第一个Docker应用栈&nbsp;&nbsp;16<br/>2.3.1&nbsp;Docker集群部署&nbsp;&nbsp;16<br/>2.3.2&nbsp;第一个Hello World&nbsp;&nbsp;17<br/>2.3.3&nbsp;开发、测试和发布一体化&nbsp;&nbsp;27', '004.jpg',63,' 人民邮电出版社','2015-09-01',647); 
insert into books values('B005','战国纵横：鬼谷子的局', 283.50, 1.0, 'Cudy', '本书从实践者的角度，在讲解Docker高级实践技巧的同时，深入到源代码层次，为读者梳理出Docker容器技术和基于Docker的容器云技术（如Kubernetes）的实现方法和设计思路，帮助读者理解如何在实际场景中利用Docker解决问题并启发新的思考。', '第一部分&nbsp;Docker深入解读<br/>第1章&nbsp;从容器到容器云&nbsp;&nbsp;2<br/>1.1&nbsp;云计算平台&nbsp;&nbsp;2<br/>1.2&nbsp;容器，新的革命&nbsp;&nbsp;3<br/>1.3&nbsp;进化：从容器到容器云&nbsp;&nbsp;7<br/>第2章&nbsp;Docker基础&nbsp;&nbsp;8<br/>2.1&nbsp;Docker的安装&nbsp;&nbsp;8<br/>2.2&nbsp;Docker操作参数解读&nbsp;&nbsp;9<br/>2.3&nbsp;搭建你的第一个Docker应用栈&nbsp;&nbsp;16<br/>2.3.1&nbsp;Docker集群部署&nbsp;&nbsp;16<br/>2.3.2&nbsp;第一个Hello World&nbsp;&nbsp;17<br/>2.3.3&nbsp;开发、测试和发布一体化&nbsp;&nbsp;27', '005.jpg',55,' 人民邮电出版社','2015-09-01',8723); 
insert into books values('B006','微人格心理学 ', 37.52, 0.5, 'Jeff', '本书从实践者的角度，在讲解Docker高级实践技巧的同时，深入到源代码层次，为读者梳理出Docker容器技术和基于Docker的容器云技术（如Kubernetes）的实现方法和设计思路，帮助读者理解如何在实际场景中利用Docker解决问题并启发新的思考。', '第一部分&nbsp;Docker深入解读<br/>第1章&nbsp;从容器到容器云&nbsp;&nbsp;2<br/>1.1&nbsp;云计算平台&nbsp;&nbsp;2<br/>1.2&nbsp;容器，新的革命&nbsp;&nbsp;3<br/>1.3&nbsp;进化：从容器到容器云&nbsp;&nbsp;7<br/>第2章&nbsp;Docker基础&nbsp;&nbsp;8<br/>2.1&nbsp;Docker的安装&nbsp;&nbsp;8<br/>2.2&nbsp;Docker操作参数解读&nbsp;&nbsp;9<br/>2.3&nbsp;搭建你的第一个Docker应用栈&nbsp;&nbsp;16<br/>2.3.1&nbsp;Docker集群部署&nbsp;&nbsp;16<br/>2.3.2&nbsp;第一个Hello World&nbsp;&nbsp;17<br/>2.3.3&nbsp;开发、测试和发布一体化&nbsp;&nbsp;27', '006.jpg',324,' 人民邮电出版社','2015-09-01',653); 
insert into books values('B007','FBI心理学与读心术（全套5本）职场与生', 83.51, 1.0, 'Son', '本书从实践者的角度，在讲解Docker高级实践技巧的同时，深入到源代码层次，为读者梳理出Docker容器技术和基于Docker的容器云技术（如Kubernetes）的实现方法和设计思路，帮助读者理解如何在实际场景中利用Docker解决问题并启发新的思考。', '第一部分&nbsp;Docker深入解读<br/>第1章&nbsp;从容器到容器云&nbsp;&nbsp;2<br/>1.1&nbsp;云计算平台&nbsp;&nbsp;2<br/>1.2&nbsp;容器，新的革命&nbsp;&nbsp;3<br/>1.3&nbsp;进化：从容器到容器云&nbsp;&nbsp;7<br/>第2章&nbsp;Docker基础&nbsp;&nbsp;8<br/>2.1&nbsp;Docker的安装&nbsp;&nbsp;8<br/>2.2&nbsp;Docker操作参数解读&nbsp;&nbsp;9<br/>2.3&nbsp;搭建你的第一个Docker应用栈&nbsp;&nbsp;16<br/>2.3.1&nbsp;Docker集群部署&nbsp;&nbsp;16<br/>2.3.2&nbsp;第一个Hello World&nbsp;&nbsp;17<br/>2.3.3&nbsp;开发、测试和发布一体化&nbsp;&nbsp;27', '007.jpg',523,' 人民邮电出版社','2015-09-01',763); 
insert into books values('B008','图灵程序设计丛书：图解密码技术 ', 62.74, 0.66, 'of', '本书从实践者的角度，在讲解Docker高级实践技巧的同时，深入到源代码层次，为读者梳理出Docker容器技术和基于Docker的容器云技术（如Kubernetes）的实现方法和设计思路，帮助读者理解如何在实际场景中利用Docker解决问题并启发新的思考。', '第一部分&nbsp;Docker深入解读<br/>第1章&nbsp;从容器到容器云&nbsp;&nbsp;2<br/>1.1&nbsp;云计算平台&nbsp;&nbsp;2<br/>1.2&nbsp;容器，新的革命&nbsp;&nbsp;3<br/>1.3&nbsp;进化：从容器到容器云&nbsp;&nbsp;7<br/>第2章&nbsp;Docker基础&nbsp;&nbsp;8<br/>2.1&nbsp;Docker的安装&nbsp;&nbsp;8<br/>2.2&nbsp;Docker操作参数解读&nbsp;&nbsp;9<br/>2.3&nbsp;搭建你的第一个Docker应用栈&nbsp;&nbsp;16<br/>2.3.1&nbsp;Docker集群部署&nbsp;&nbsp;16<br/>2.3.2&nbsp;第一个Hello World&nbsp;&nbsp;17<br/>2.3.3&nbsp;开发、测试和发布一体化&nbsp;&nbsp;27', '008.jpg',65,' 人民邮电出版社','2015-09-01',452); 
insert into books values('B009','电子工程师必备 元器件应用宝典 强化版 ', 62.86, 1.0, 'bitch', '本书从实践者的角度，在讲解Docker高级实践技巧的同时，深入到源代码层次，为读者梳理出Docker容器技术和基于Docker的容器云技术（如Kubernetes）的实现方法和设计思路，帮助读者理解如何在实际场景中利用Docker解决问题并启发新的思考。', '第一部分&nbsp;Docker深入解读<br/>第1章&nbsp;从容器到容器云&nbsp;&nbsp;2<br/>1.1&nbsp;云计算平台&nbsp;&nbsp;2<br/>1.2&nbsp;容器，新的革命&nbsp;&nbsp;3<br/>1.3&nbsp;进化：从容器到容器云&nbsp;&nbsp;7<br/>第2章&nbsp;Docker基础&nbsp;&nbsp;8<br/>2.1&nbsp;Docker的安装&nbsp;&nbsp;8<br/>2.2&nbsp;Docker操作参数解读&nbsp;&nbsp;9<br/>2.3&nbsp;搭建你的第一个Docker应用栈&nbsp;&nbsp;16<br/>2.3.1&nbsp;Docker集群部署&nbsp;&nbsp;16<br/>2.3.2&nbsp;第一个Hello World&nbsp;&nbsp;17<br/>2.3.3&nbsp;开发、测试和发布一体化&nbsp;&nbsp;27', '009.jpg',873,' 人民邮电出版社','2015-09-01',7732); 
insert into books values('B010','开关电源设计（第3版） ', 33.64, 0.98, 'Jucy', '本书从实践者的角度，在讲解Docker高级实践技巧的同时，深入到源代码层次，为读者梳理出Docker容器技术和基于Docker的容器云技术（如Kubernetes）的实现方法和设计思路，帮助读者理解如何在实际场景中利用Docker解决问题并启发新的思考。', '第一部分&nbsp;Docker深入解读<br/>第1章&nbsp;从容器到容器云&nbsp;&nbsp;2<br/>1.1&nbsp;云计算平台&nbsp;&nbsp;2<br/>1.2&nbsp;容器，新的革命&nbsp;&nbsp;3<br/>1.3&nbsp;进化：从容器到容器云&nbsp;&nbsp;7<br/>第2章&nbsp;Docker基础&nbsp;&nbsp;8<br/>2.1&nbsp;Docker的安装&nbsp;&nbsp;8<br/>2.2&nbsp;Docker操作参数解读&nbsp;&nbsp;9<br/>2.3&nbsp;搭建你的第一个Docker应用栈&nbsp;&nbsp;16<br/>2.3.1&nbsp;Docker集群部署&nbsp;&nbsp;16<br/>2.3.2&nbsp;第一个Hello World&nbsp;&nbsp;17<br/>2.3.3&nbsp;开发、测试和发布一体化&nbsp;&nbsp;27', '010.jpg',23,' 人民邮电出版社','2015-09-01',782);
 
//增加分类与书籍的关系信息
insert into bookcategory values('B001','C001');
insert into bookcategory values('B002','C001');
insert into bookcategory values('B003','C001');
insert into bookcategory values('B004','C002');
insert into bookcategory values('B005','C002');
insert into bookcategory values('B006','C003');
insert into bookcategory values('B007','C002');
insert into bookcategory values('B007','C003');
insert into bookcategory values('B008','C001');
insert into bookcategory values('B008','C004');
insert into bookcategory values('B009','C004');
insert into bookcategory values('B010','C004');
